os: linux
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
before_install:
  - openssl aes-256-cbc -K $encrypted_531087c7d488_key -iv $encrypted_531087c7d488_iv
    -in travis_id_rsa.enc -out ~/.ssh/travis_id_rsa -d
  - chmod 600 ~/.ssh/travis_id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/travis_id_rsa
  - git config --global user.name "Travis Bot"
  - git config --global user.email me@makergyt.com

script:
  - npm run clean
  - YUQUE_TOKEN=$YUQUE_TOKEN npm run sync
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  token: $GH_TOKEN
  keep_history: true
  local_dir: public
  on:
    branch: master

after_success:
  - git add --all
  - git commit -m":bird:yuque auto update"
  - git push -u git@github.com:MakerGYT/Trigger.git HEAD:master --force